
## Server Security

# With a whitelist enabled, users not on the whitelist cannot connect. Ops are automatically whitelisted.
white-list=false


## World and biome settings

# Sets the starting value for the world.
level-seed=4025804172371830787
           

# This determines the server-side viewing distance.
# 10 is the default/recommended value - a lower value saves resources.
view-distance=10


## Game mechanics

# The maximum number of players that can play on the server at the same time.
# 20 is the default value. The fewer players play, the better the performance at low resources.
max-players=10